spring.application.name: api-server
spring.profiles.active: local

spring:
  config:
    import:
      - logging.yml
      - kafka.yml
      - jpa.yml
  kafka:
    consumer:
      group-id: pang-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

---
spring.config.activate.on-profile: local
server:
  port: 8081

spring:
  kafka:
    consumer:
      group-id: pang-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live